apiVersion: batch/v1
kind: Job
metadata:
  name: init-config-server
  namespace: mongo-shard
spec:
  template:
    spec:
      containers:
        - name: init-config-server
          image: mongo:5.0
          command: ["/bin/sh", "-c"]  # Use shell to run multiple commands
          args:
            - |
              mongosh --port 27019 --eval "rs.initiate();"
              mongosh --port 27019 --eval "var cfg = rs.conf(); cfg.members[0].host='config-server-0.config-server:27019'; rs.reconfig(cfg);"
              mongosh --port 27019 --eval "rs.add('config-server-1.config-server:27019'); rs.add('config-server-2.config-server:27019');"
      restartPolicy: OnFailure

