---
- name: Deploy to EKS Cluster
  hosts: all
  tasks:
    - name: Create Kubernetes Deployment
      kubernetes.core.k8s:
        kubeconfig: /path/to/kubeconfig
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: nginx-deployment
            labels:
              app: nginx
          spec:
            replicas: 2
            selector:
              matchLabels:
                app: nginx
            template:
              metadata:
                labels:
                  app: nginx
              spec:
                containers:
                - name: nginx
                  image: nginx:1.14.2
                  ports:
                  - containerPort: 80
