apiVersion: v1
kind: Namespace
metadata:
  name: node-installer
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-installer
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: node-installer
  template:
    metadata:
      labels:
        name: node-installer
    spec:
      hostPID: true
      containers:
        - name: install-nfs-common
          image: ubuntu:20.04
          securityContext:
            privileged: true
          command:
            - sh
            - -c
            - |
              apt-get update && apt-get install -y nfs-common || true
              while true; do sleep 3600; done
      restartPolicy: Always
      tolerations:
        - key: node.kubernetes.io/not-ready
          operator: Exists
          effect: NoExecute
        - key: node.kubernetes.io/unreachable
          operator: Exists
          effect: NoExecute
