apiVersion: batch/v1
kind: Job
metadata:
  name: add-shards
spec:
  template:
    spec:
      containers:
        - name: add-shards
          image: mongo:latest
          command:
            [
              "mongo",
              "--eval",
              "sh.addShard('shard1ReplSet/shard1-0.shard1:27017'); sh.addShard('shard2ReplSet/shard2-0.shard2:27017');",
            ]
      restartPolicy: OnFailure
