apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: config-server
  namespace: mongo-shard
spec:
  serviceName: "config-server"
  replicas: 3
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: mongo:5.0
          command: 
          - mongod
          - "--bind_ip_all"
          - "--port"
          - "27019"
          - "--configsvr" 
          - "--replSet" 
          - "configReplSet" 
          ports:
            - containerPort: 27019
          resources:
            requests:
              memory: 512Mi
              cpu: 500m
            limits:
              memory: 512Mi
              cpu: 500m
  #         volumeMounts:
  #           - name: shard2-data
  #             mountPath: /data/db
  # volumeClaimTemplates:
  #   - metadata:
  #       name: shard2-data
  #     spec:
  #       accessModes: ["ReadWriteMany"]
  #       storageClassName: "nfs-client"
  #       resources:
  #         requests:
  #           storage: 1Gi


