apiVersion: v1
kind: Service
metadata:
  name: config-server
  namespace: mongo-shard
spec:
  ports:
    - protocol: TCP
      name: mongo
      port: 27019
      targetPort: 27019
  clusterIP: None
  selector:
    app: config-server