---
- name: Install NFS Common on EKS Nodes
  hosts: eks_nodes
  become: yes
  tasks:
    - name: Update apt cache (for Debian/Ubuntu-based systems)
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install nfs-common (for Debian/Ubuntu-based systems)
      apt:
        name: nfs-common
        state: present
      when: ansible_os_family == "Debian"

    - name: Install nfs-utils (for RedHat/CentOS-based systems)
      yum:
        name: nfs-utils
        state: present
      when: ansible_os_family == "RedHat"
