apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongos
  namespace: mongo-shard
spec:
  selector:
    matchLabels:
      role: mongos
  template:
    metadata:
      labels:
        role: mongos
    spec:
      containers:
        - name: mongos
          image: mongo:latest
          command:
            - mongos
            - "--configdb"
            - "configReplSet/config-server-0.config-server.mongo-shard.svc.cluster.local:27019,config-server-1.config-server.mongo-shard.svc.cluster.local:27019,config-server-2.config-server.mongo-shard.svc.cluster.local:27019"          ports:
          ports:
            - containerPort: 27017
          resources:
            requests:
              memory: 512Mi
              cpu: 500m
            limits:
              memory: 512Mi
              cpu: 500m
