apiVersion: batch/v1
kind: Job
metadata:
  name: init-shard2
  namespace: mongo-shard
spec:
  template:
    spec:
      containers:
        - name: init-shard2
          image: mongo:latest
          command:
            [
              "mongo",
              "--eval",
              "rs.initiate({_id: 'shard2ReplSet', members: [{ _id : 0, host : 'shard2-0.shard2:27017' }, { _id : 1, host : 'shard2-1.shard2:27017' }, { _id : 2, host : 'shard2-2.shard2:27017' }]})",
            ]
      restartPolicy: OnFailure
