apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
  namespace: mongo-shard
data:
  database_url: mongos

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-deployment
  namespace: mongo-shard
spec:
  replicas: 2
  selector:
    matchLabels:
      app: express
  template:
    metadata:
      labels:
        app: express
    spec:
      containers:
      - name: express
        image: mongo-express:latest  # Replace with your actual Express image
        ports:
        - containerPort: 8081  # Assuming your Express app runs on port 3000
        env:
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom: 
            configMapKeyRef:
              name: mongodb-configmap
              key: database_url
---
apiVersion: v1
kind: Service
metadata:
  name: express-service
  namespace: mongo-shard
spec:
  type: NodePort  # Change to NodePort if LoadBalancer is not supported in your cluster
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app: express
