apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
  namespace: mongo-shard
data:
  database_url: mongos

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongo-express
  name: mongo-express
  namespace: mongo-shard
spec:
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
        - name: mongo-express
          # image: mongo-express # connects but Turn on admin in config.js to view server stats!
          # image: mongo-express:latest # connects but  Turn on admin in config.js to view server stats!
          image: mongo-express:0.54.0
          # image: mongo-express:0.54
          imagePullPolicy: 'Always'
          ports:
            - containerPort: 8081
              protocol: TCP

          resources:
            limits:
              memory: '1Gi'
              cpu: '100m'
          env:
          - name: ME_CONFIG_MONGODB_SERVER
            valueFrom: 
              configMapKeyRef:
                name: mongodb-configmap
                key: database_url
---
apiVersion: v1
kind: Service
metadata:
  name: express-service
  namespace: mongo-shard
spec:
  ports:
  - name: http
    port: 8081
    targetPort: 8081
    protocol: TCP
  selector:
    app: express

