apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: shard2
  namespace: mongo-shard
spec:
  serviceName: "shard2"
  replicas: 3
  selector:
    matchLabels:
      role: shard2
  template:
    metadata:
      labels:
        role: shard2
    spec:
      containers:
        - name: shard2
          image: mongo:latest
          command:
          - mongod
          - "--bind_ip_all"
          - "--replSet" 
          - shard2ReplSet
          ports:
            - containerPort: 27017
          resources:
            requests:
              memory: 512Mi
              cpu: 500m
            limits:
              memory: 512Mi
              cpu: 500m
  #         volumeMounts:
  #           - name: shard2-data
  #             mountPath: /data/db
  # volumeClaimTemplates:
  #   - metadata:
  #       name: shard2-data
  #     spec:
  #       accessModes: ["ReadWriteMany"]
  #       storageClassName: "nfs-client"
  #       resources:
  #         requests:
  #           storage: 1Gi
